<?php
    // Set page title.
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    //var_dump(get_class($this->catalog));
    //echo $this->catalog->getPatronGroup();
    //echo "***********";
    //echo ($this->catalog->patronCanRequestDelivery());
    //echo "***********";
    //if ($this->catalog->patronCanRequestDelivery()) echo "can deliver";
    $itemLocation = $_GET['library'];
    $callNo = $_GET['callNo'];
    $barcode = $_GET['itemBarcode'];
    //echo $itemLocation;
    //echo "----------------";
    //echo $this->catalog->getPatronCampusAddress();
    $noPickupMessage = null;
    if (!$this->catalog->patronCanRequestDelivery()){ 
      $this->pickup = false;
      $noPickupMessage = "Material will be held for pickup at the " . $itemLocation . " Library for 5 business days.";
    }
    else {
        //CEDE PICKUP LOCATION OF DELIVERY AND ITEM HOME LOCATON
        $allLocationNames = $this->catalog->getLocationNames();
        $fairChild = $allLocationNames["Fairchild Martindale"];
        $linderman = $allLocationNames["Linderman"];
        $delivery = $allLocationNames["Delivery"];
        $locations = [];
        if (strpos($itemLocation, 'Fairchild') !== false) { 
          //home location is fairchild
          $one = array('locationID' => $fairChild, 'locationDisplay' => 'Fairchild');
          $two = array('locationID' => $delivery, 'locationDisplay' => 'Delivery');
        }
        else {
          $one = array('locationID' => $linderman, 'locationDisplay' => 'Linderman');
          $two = array('locationID' => $delivery, 'locationDisplay' => 'Delivery');
        }
        array_push($locations,$one);
        array_push($locations,$two);
        $this->pickup = $locations;
    }
  

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
        . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';
?>
<h2><?=$this->transEsc('request_place_text')?></h2>
<?php if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<?php endif; ?>

<form class="form-record-hold" method="post" name="placeHold" data-clear-account-cache="holds">
  <input type="hidden" name="gatheredDetails[homeLocation]" value="<?=$itemLocation?>">
  <?php $t = iconv('UTF-8','ASCII//TRANSLIT', $this->driver->getShortTitle()); ?>
	<?php $c = iconv('UTF-8','ASCII//TRANSLIT', $callNo); ?>
  <?php $b = iconv('UTF-8','ASCII//TRANSLIT', $barcode); ?>
  <input type="hidden" name="gatheredDetails[itemTitle]" value="<?= $t ?>"/>
	<input type="hidden" name="gatheredDetails[callNo]" value="<?= $c ?>" />
  <input type="hidden" name="gatheredDetails[barcode]" value="<?= $b ?>" />
  <?=$this->flashmessages()?>

  <?php
    if ($noPickupMessage != null) {
      echo "<h2>". $noPickupMessage . "</h2>";
    }
  ?>

  <h2><b>Title:</b>
  <class="form-control-static"><?=$this->driver->getBreadcrumb() ?></p></h2>


  
  <?php if (in_array("requiredByDate", $this->extraHoldFields)): ?>
    <div class="form-group hold-required-by">
      <label class="control-label"><?=$this->transEsc("hold_required_by")?>:</label>
      <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="form-control"/>
      (<?=$this->dateTime()->getDisplayDateFormat()?>)
    </div>
  <?php endif; ?>



  <?php if ($this->requestGroupNeeded): ?>
    <div class="form-group hold-request-group">
      <?php
        if (isset($this->gatheredDetails['requestGroupId']) && $this->gatheredDetails['requestGroupId'] !== "") {
            $selected = $this->gatheredDetails['requestGroupId'];
        } else {
            $selected = $this->defaultRequestGroup;
        }
     ?>
      <label class="control-label"><?=$this->transEsc("hold_request_group")?>:</label>
      <select id="requestGroupId" name="gatheredDetails[requestGroupId]" class="form-control">
        <?php if ($selected === false): ?>
          <option value="" selected="selected">
            <?=$this->transEsc('select_request_group')?>
          </option>
        <?php endif; ?>
        <?php foreach ($this->requestGroups as $group): ?>
          <option value="<?=$this->escapeHtmlAttr($group['id'])?>"<?=($selected == $group['id']) ? ' selected="selected"' : ''?>>
            <?=$this->transEsc('request_group_' . $group['name'], null, $group['name'])?>
          </option>
        <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>

  <?php if (in_array("pickUpLocation", $this->extraHoldFields)): ?>
    <?php
      if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
        $selected = $this->gatheredDetails['pickUpLocation'];
      } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
        $selected = $this->homeLibrary;
      } else {
        $selected = $this->defaultPickup;
      }
    ?>





    <?php if ($this->requestGroupNeeded): ?>
      <div class="form-group hold-pickup-location">
        <label id="pickUpLocationLabel" class="control-label"><i></i> <?=$this->transEsc("pick_up_location")?>:
          <?php if (in_array("requestGroup", $this->extraHoldFields)): ?>
            <noscript> (<?=$this->transEsc("Please enable JavaScript.")?>)</noscript>
          <?php endif; ?>
        </label>
        <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" data-default="<?=$this->escapeHtmlAttr($selected)?>" class="form-control">
          <?php if ($selected === false): ?>
          <option value="" selected="selected">
            <?=$this->transEsc('select_pickup_location')?>
          </option>
          <?php endif; ?>
        </select>
      </div>
    <?php elseif ($this->pickup): ?>
    
      <div class="form-group hold-pickup-location">
        <label class="control-label"><?=$this->transEsc("pick_up_location")?>:</label>
        <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" class="form-control">
          <?php if ($selected === false && count($this->pickup) > 1): ?>
            <option value="" selected="selected">
              <?=$this->transEsc('select_pickup_location')?>
            </option>
          <?php endif; ?>
          <?php foreach ($this->pickup as $lib): ?>
            <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
              <?=$this->transEscWithPrefix('location_', $lib['locationDisplay'])?>
            </option>
          <?php endforeach; ?>
        </select>
      </div>
    <?php else: ?>
      <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
    <?php endif; ?>
  <?php endif; ?>

<?php if ($this->catalog->patronCanRequestDelivery()): ?>
  <?php if (in_array("address-comments", $this->extraHoldFields)): ?>
    <div class="form-group hold-comment">
      <label class="control-label"><?=$this->transEsc("If selecting delivery please verify your campus address")?>:</label>
      <textarea rows="3" cols="20" name="gatheredDetails[address-comments]" class="form-control"><?=isset($this->gatheredDetails['address-comments']) ? $this->escapeHtml($this->gatheredDetails['address-comments']) : ''?><?=$this->catalog->getPatronCampusAddress()?></textarea>
    </div>
  <?php endif; ?>
  <?php endif; ?>

  <?php if (in_array("comments", $this->extraHoldFields)): ?>
    <div class="form-group hold-comment">
      <label class="control-label"><?=$this->transEsc("Comments")?>:</label>
      <textarea rows="3" cols="20" name="gatheredDetails[comment]" class="form-control"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
    </div>
  <?php endif; ?>



  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>
  </div>
</form>

<?php
    // Set up hold script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('hold.js');

    $js = <<<JS
        if ($.isReady) {
            setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
        } else {
            $(document).ready(function(){
                setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
            });
        }
JS;

    echo $this->inlineScript()->appendScript($js);
?>
