

<h1>Article Search Help:</h1>

<h2>FAQ</h2>

<ul>

  <li>What if I cannot find a specific article?</li>

      <ul>

          <li>Request a copy of the article using <a href="https://illiad.lib.lehigh.edu/illiad/logon.html" target="_illiad">Illiad</a>.  <!--The turn-around time for these requests is .... on average.--></li>

          <li>Contact a subject librarian for help.   <a href="https://library.lehigh.edu/about/library-staff" target="_libs">The Librarians at Lehigh</a> are experts in many of the fields taught here.</li>


          <li>Try finding the article with <a target="_google" href="https://scholar.google.com/">Google Scholar</a>.  If you have <a href="https://scholar.google.com/scholar_settings?authuser=0#2" target="_ll">Library Links</a> set to Lehigh University, you will be taken to the SFX screen to connect to the full text if Lehigh has access or to request the article via ILLiad if we do not have access.
          </li>


</ul>