

var searchFields = new Array();
<?php foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
  searchFields["<?=$this->escapeHtml($searchVal)?>"] = "<?=$this->transEsc($searchDesc)?>";
<?php endforeach; ?>
var searchJoins = new Array();
searchJoins["AND"]  = "<?=$this->transEsc("search_AND")?>";
searchJoins["OR"]   = "<?=$this->transEsc("search_OR")?>";
searchJoins["NOT"]  = "<?=$this->transEsc("search_NOT")?>";
var addSearchString = "<?=$this->transEsc("add_search")?>";
var searchLabel     = "<?=$this->transEsc("adv_search_label")?>";
var searchFieldLabel = "<?=$this->transEsc("in")?>";
var deleteSearchGroupString = "<?=$this->transEsc("del_search")?>";
var searchMatch     = "<?=$this->transEsc("search_match")?>";
var searchFormId    = 'advSearchForm';




var i18n = new Array();
i18n['in'] = "<?=$this->transEsc("in")?>";
i18n['AND'] = "<?=$this->transEsc("AND")?>";
i18n['OR'] = "<?=$this->transEsc("OR")?>";
i18n['NOT'] = "<?=$this->transEsc("NOT")?>";

