
<style>
.group
{
  background: #eee; 
  border: 1px solid #c8c8c8; 
  border-radius: 4px;
  margin: 0 0 6px;
  padding: 10px 10px 10px 25px;
}
.group .add_search_link
{
  display: inline-block;
  margin-top: 4px;
}
.group [class^=col-]
{
  padding-left: 0;
}
.group .search
{
  margin-bottom: 2px;
}
#groupPlaceHolder
{
  display: block;
  padding: 6px;
}


</style>


<?php
    // Set page title.
    $this->headTitle($this->translate('Advanced Search'));

    // Disable top search box -- this page has a special layout.
    $this->layout()->searchbox = false;

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Catalog Advanced Search') . '</em>';

?>
    <?php
    $baseUrl = "http://$_SERVER[HTTP_HOST]";
    $articleBasicSearch = $baseUrl . "/Search";

    ?>

    <a href="<?= $articleBasicSearch?>">Back to Catalog Basic Search</a>
    <br>
<?php
    // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
        $searchFilters = $this->saved->getParams()->getFilterList();
    } else {
        $searchDetails = $searchFilters = $groups = false;
    }

    // Set up Javascript:
    // Step 1: Define our search arrays so they are usuable in the javascript
    $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
    // Step 2: Call the javascript to make use of the above
    $this->headScript()->appendFile('advanced_search_adv.js');
    // Step 3: Build the page
    $this->headScript()->appendScript($this->partial('search/advanced/build_page.phtml', array('searchDetails' => $searchDetails)));
?>

<form method="get" action="<?=$this->url($this->options->getSearchAction())?>" id="advSearchForm" name="searchForm" class="search">
  <div class="span-25">

    <h3><?=$this->transEsc('Catalog Advanced Search')?></h3>

        
    <div class="advSearchContent">
      <?=$this->flashmessages()?>
      

      <? /* An empty div. This is the target for the javascript that builds this screen */ ?>
      <div id="searchHolder" style="width:100%">
        <?php /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
        <noscript>
        <?php if ($groups !== false) {
               $numGroups = count($groups);
           }
           if (!isset($numGroups) || $numGroups < 3) {
               $numGroups = 3;
           }
        ?>
        <?php for ($i = 0; $i < $numGroups; $i++): ?>
          <div class="row group group<?=$i%2?>" id="group<?=$i?>">
            <div class="groupSearchDetails" style="margin-right:40px">
              <div class="join">
                <label for="search_bool<?=$i?>"><?=$this->transEsc("search_match")?>:</label>
                <select id="search_bool<?=$i?>" name="bool<?=$i?>[]">
                  <?php
                    $options = array('AND', 'OR', 'NOT');
                    foreach ($options as $option) {
                        echo '<option value="' . $this->escapeHtml($option) . '"';
                        if ($groups && isset($groups[$i])) {
                            $operator = $groups[$i]->isNegated() ? 'NOT' : $groups[$i]->getOperator();
                            if ($operator == $option) {
                                echo ' selected="selected"';
                            }
                        }
                        echo '>' . $this->transEsc('search_' . $option) . '</option>';
                    }
                  ?>
                </select>
              </div>
            </div>
            <div class="groupSearchHolder" id="group<?=$i?>SearchHolder">
            <?php
              if (isset($group[$i])) {
                  $currentGroup = $group[$i]->getQueries();
                  $numRows = count($currentGroup);
              } else {
                  $currentGroup = false;
              }
              if (!isset($numRows) || $numRows < 3) {
                  $numRows = 3;
              }
            ?>
            <?php for ($j = 0; $j < $numRows; $j++): ?>
              <?php $currRow = isset($currentGroup[$j]) ? $currentGroup[$j] : false; ?>
              <div class="advRow">
                <div class="label">
                  <label <?=($j > 0)?'class="offscreen" ':''?>for="search_lookfor<?=$i?>_<?=$j?>"><?=$this->transEsc("adv_search_label")?>:</label>&nbsp;
                </div>
                <div class="terms">
                  <input id="search_lookfor<?=$i?>_<?=$j?>" type="text" value="<?=$currRow?$this->escapeHtml($currRow->getString()):''?>" size="50" name="lookfor<?=$i?>[]"/>
                </div>
                <div class="field">
                  <label for="search_type<?=$i?>_<?=$j?>"><?=$this->transEsc("in")?></label>
                  <select id="search_type<?=$i?>_<?=$j?>" name="type<?=$i?>[]">
                  <?php foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                    <option value="<?=$this->escapeHtml($searchVal)?>"<?=($currRow && $currRow->getHandler() == $searchVal)?' selected="selected"':''?>><?=$this->transEsc($searchDesc)?></option>
                  <?php endforeach; ?>
                  </select>
                </div>
                <span class="clearer"></span>
              </div>
            <?php endfor; ?>
            </div>
          </div>
        <?php endfor; ?>
        </noscript>
      </div>

      <br>

      <span style="font-size:22px;"><a id="addGroupLink" href="#" class="add offscreen" onclick="addGroup(); return false;"><?=$this->transEsc("add_search_group")?></a></span>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <span style="font-size:22px;"><a id="clearform" class="delete" href="#" title="Clear Form" onclick="clearForm('advSearchForm'); return false;">Clear Form</a></span>

      <br/><br/>

       <?php //3-18-2018 $lastSort = $this->options->getLastSort(); if (!empty($lastSort)): ?>
	   <?php if (!empty($lastSort)):  ?>
	   <?php $lastSort = $this->searchMemory()->getLastSort($this->searchClassId); ?>
        <input type="hidden" name="sort" value="<?=$this->escapeHtml($lastSort)?>" />
      <?php endif; ?>
      <input type="submit" name="submit" class="btn btn-primary btn-lg" value="<?=$this->transEsc("Find")?>"/>
      <?php if (isset($this->extraAdvancedControls)): ?>
        <?=$this->extraAdvancedControls?>
        <input type="submit" name="submit" class="btn btn-primary btn-lg" value="<?=$this->transEsc("Find")?>"/>
      <?php endif; ?>
    </div>
  </div>



  <div class="clear"></div>
</form>

