<?php
  // Load search actions and settings (if any):
  $options = $this->searchOptions($searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  $noJsSupport = $this->config()->nonJavascriptSupportEnabled();
?>
<?php if (!empty($facetList)): ?>
  <div class="search-home-facets">
    <?php foreach ($facetList as $field => $details): ?>
      <?php if ($isHierarchy = in_array($field, $hierarchicalFacets ?? [])):
          $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');
          $this->headScript()->appendFile('facets.js');
          $sort = $hierarchicalFacetSortOptions[$field] ?? $hierarchicalFacetSortOptions['*'] ?? 'all';
          $script = <<<JS
$(document).ready(function() {
  $('#facet_{$this->escapeHtml($field)}_container').removeClass('hide');
  initFacetTree($('#facet_{$this->escapeHtml($field)}'), false);
});
JS;
          echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
        ?>
        <div id="facet_<?=$this->escapeHtml($field)?>_container" class="home-facet <?=$this->escapeHtmlAttr($field)?> hide">
          <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
          <div id="facet_<?=$this->escapeHtml($field)?>" class="jstree-facet"
              data-source="<?=$this->escapeHtml($this->searchClassId)?>"
              data-facet="<?=$this->escapeHtml($field)?>"
              data-path="<?=$this->url($basicSearch)?>"
              data-exclude="0"
              data-operator="AND"
              data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
              data-sort="<?=$sort?>">
          </div>
        </div>
        <noscript>
          <?php if (!$noJsSupport): ?>
            <h2><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></h2>
            <?=$this->transEsc('Please enable JavaScript.')?>
          <?php endif; ?>
      <?php endif; ?>
      <?php if (!$isHierarchy || $noJsSupport): // do we need regular display? ?>
        <?php $sortedList = $this->sortFacetList($results, $field, $details['list'], $basicSearch); ?>
        <div class="home-facet <?=$this->escapeHtmlAttr($field) ?>">
          

        </div>
      <?php endif; ?>
      <?php if ($isHierarchy): // close tag opened in matching if above ?>
        </noscript>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
