<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <p><strong></strong></p>
      <style>
        .btn-primary-reshare, .btn-primary-reshare:hover, .btn-primary-reshare:focus, .btn-primary-reshare:active, .btn-primary-reshare:visited{
          background-color: #007ebd !important;
	        border-color: #007ebd !important;
          color: white !important;
          outline: none !important;
          font-size: 1.5em;
        }
      </style>

      <ul>

      </ul>
    </div>
    <div class="footer-column">
      <p><strong></strong></p>
      <ul>
       
      </ul>
    </div>
    <div class="footer-column">
      <p><strong></strong></p>
      <ul>

      </ul>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
