<?php $account = $this->auth()->getManager(); ?>
<div class="banner container navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
   
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul role="navigation" class="nav navbar-nav navbar-right flip">
          <li>
              <a id="libHomePage" href="http://library.lehigh.edu"><i class="fa fa-home"></i> <?=$this->transEsc("Library Home Page")?></a>
          </li>
 	  <li>
              <a id="libChat" href="https://lts.lehigh.edu/chat" target="new"><i class="fa fa-comment fa-1x" aria-hidden="true"></i> <?=$this->transEsc("Need help? Chat with us!")?></a>
          </li>
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <?php endif; ?>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <?php if($account->dropdownEnabled()): ?>
              <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li>
            <?php endif; ?>
            <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                      <?=$this->transEsc($current['desc']) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode])) ?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
	  
	  
	          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Help")?> <b class="caret"></b></a>
                 <ul class="dropdown-menu">

                    <li>
                      <a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Catalog Search Tips')?>"><?=$this->transEsc('Catalog Search Tips')?></a></li>

                      <li>
                      <a href="<?=$this->url('help-home')?>?topic=articlesearch" class="help-link" title="<?=$this->transEsc('Article Search Tips')?>"><?=$this->transEsc('Article Search Tips')?></a></li>
                   
                   
                      <?php if ($this->feedback()->tabEnabled()): ?>
                        <li>
                          <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc("Feedback")?></a>
                        </li>
                      <?php endif; ?>

                   <li><a href="https://library.lehigh.edu/content/e_zborrow_authentication" target="new">Can't find a book?  Order from PALCI</a></li>
             </ul>
          </li>




        <!--WAITING UNTIL WE START ADDING NEW
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php //=$this->transEsc("New")?> <b class="caret"></b></a>
                 <ul class="dropdown-menu">
                      <li><a href="javascript:newbooks()" id="newvideos">New Books</a></li>
                       <li><a href="javascript:newvideos()" id="newvideos">New Videos</a></li>
                 </ul>
          </li> -->

          <li>
            <a href="<?=$this->url('search-reserves')?>"><i class="fa fa-tag"></i><?=$this->transEsc('Course Reserves')?></a>
          </li>
        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>
<div class="container">
<div class="row">
  <div class="col-md-6">
    <h1>
    <a title="Lehigh University - Library Catalog" href="http://lehigh.edu" target="new"><img alt="Lehigh University - Library Catalog" src="<?=$this->imageLink('download.jpg')?>" style="width: 15%; height: 15%"></a>
    <a title="Lehigh University - Library Catalog" href="../"><img src="<?=$this->imageLink('asalibrarycatalog.png')?>" style="width: 82%; height: 82%"></a>
  </h1>
  </div>
  <div class="col-md-6">













       

  </div>
</div>
</div>

<br>
<?php if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <nav class="nav searchbox hidden-print">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>
<?php endif; ?>
