<?php if ((strlen($holding['barcode'] ?? '') > 0) or (strlen($holding['callnumber'] ?? '') > 0)): ?>
  <?php


    $check = $holding['check'] ?? false;
    $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
    $checkILLRequest = $holding['checkILLRequest'] ?? false;

    //LEHIGH


					 $t = iconv('UTF-8','ASCII//TRANSLIT', $this->driver->getShortTitle());
					 $a = iconv('UTF-8','ASCII//TRANSLIT', $this->driver->getPrimaryAuthor());
           $c = iconv('UTF-8','ASCII//TRANSLIT', $holding['callnumber']);
           $b = iconv('UTF-8','ASCII//TRANSLIT', $holding['barcode']);
           $firstName = '';
           $lastName = '';
           if (isset($user)) {
             $firsName = $user->firstName;
             $lastName = $user->lastName;
           }

           $l = "";
           $actualLocation = $holding['actualLocation'];
           if (strpos($actualLocation,'erman') !== false) 
              $l = "Linderman";
           else 
              $l = "Fairchild Martindale";
          
          


  ?>
  <tr vocab="http://schema.org/" typeof="Offer">
    <th class="copy-number"><?=$this->escapeHtml($holding['callnumber'])?>
      <?php if ($holding['enumchron'] ?? false): ?>
        <span class="enumchron">(<?=$this->escapeHtml($holding['enumchron'])?>)</span>
      <?php endif; ?>         
    </th>
    <td>
      <?php if ($holding['reserve'] == "Y"): ?>
        <link property="availability" href="http://schema.org/InStoreOnly" />
        <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
      <?php endif; ?>
      <?php if ($holding['use_unknown_message'] ?? false): ?>
        <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
      <?php else: ?>
        <?php if ($holding['availability'] ?? false): ?>
          <?php /* Begin Available Items (Holds) */ ?>
           <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
          <?php if ($holding['requestForm'] != null): ?>
            <a  target='new' class="<?=$check ? 'checkRequest ' : ''?>placehold" href="<?=$holding['requestFormLink']?>?callNumber=<?=$c?>&author=<?=$a?>&title=<?=$t?>&barcode=<?=$b?>&location=<?=$actualLocation?>&fistName=<?=$firstName?>&lastName=<?=$lastName?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$holding['requestForm']?></a>

          <?php elseif ($holding['addLink'] ?? false): ?>
            <a class="<?=$check ? 'checkRequest ' : ''?>placehold" <?php if (!empty($holding['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($holding['link'],false)?>&library=<?=$l?>&callNo=<?=$c?>&itemBarcode=<?=$b?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Request This")?></a>
          <?php endif; ?>
          <?php if ($holding['storageRetrievalRequestLink'] ?? false): ?>
            <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($holding['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
          <?php endif; ?>
          <?php if ($holding['ILLRequestLink'] ?? false): ?>
            <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($holding['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
          <?php endif; ?>
        <?php else: ?>
          <?php /* Begin Unavailable Items (Recalls) */ ?>
          <span class="text-danger"><?=$this->transEsc($holding['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
          <?php if ($holding['returnDate'] ?? false): ?>&ndash; <span class="small"><?=$this->escapeHtml($holding['returnDate'])?></span><?php endif; ?>
          <?php if ($holding['duedate'] ?? false): ?>
            &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($holding['duedate'])?></span>
          <?php endif; ?>
          <?php if (($holding['requests_placed'] ?? 0) > 0): ?>
            <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($holding['requests_placed'])?></span>
          <?php endif; ?>
          <?php if ($holding['link'] ?? false): ?>
            <a class="<?=$check ? 'checkRequest' : ''?> placehold" <?php if (!empty($holding['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($holding['link'],false)?>&library=<?=$l?>&callNo=<?=$c?>&itemBarcode=<?=$b?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Request This")?></a>
            |
            <span class="palciLink"><a class='palciLink' href="<?=$holding['palciLink']?>" target='new' title="<?=$this->transEsc('PALCI Request')?>">PALCI Request (fastest)</a>&nbsp;&nbsp;</span>

          <?php endif; ?>
          <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
        <?php endif; ?>
        <?php if (isset($holding['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc("Item Notes")?>:</b>
            <ul>
              <?php foreach ($holding['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      <?php endif; ?>
      <?php /* Embed item structured data: library, barcode, call number */ ?>
      <?php if ($holding['location'] ?? false): ?>
        <meta property="seller" content="<?=$this->escapeHtmlAttr($holding['location'])?>" />
      <?php endif; ?>
      <?php if ($holding['barcode'] ?? false): ?>
        <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($holding['barcode'])?>" />
      <?php endif; ?>
      <?php if ($holding['callnumber'] ?? false): ?>
        <meta property="sku" content="<?=$this->escapeHtmlAttr($holding['callnumber'])?>" />
      <?php endif; ?>
      <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
      <link property="itemOffered" href="#record" />
    </td>
  </tr>
<?php endif; ?>

      <?php if (isset($holding['location']) && $holding['location'] == "On Order"): ?>
         <?php echo "This item has been ordered.  For more information contact our acquisitions department at inord@lehigh.edu.  This item may also be available through PALCI" ?>
      <?php endif; ?>
